spring.application.name=veti

# Banco H2 (desenvolvimento)
spring.datasource.url=jdbc:h2:file:./data/fiapdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USER:ccgl}
spring.datasource.password=${DB_PASSWORD:secret}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Controller
server.servlet.context-path=/veti

#Security
api.security.token.secret=${JWT_SECRET:veti-default-secret-change-in-production}